
import Nav from '@/components/Nav'
import './globals.css'
import Footer from '@/components/Footer'
import MiniCart from '@/components/MiniCart'
import { Providers } from '@/redux/provide'
import Login from '@/components/auth/ModalAuth'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(data) {
  
  return (
    <html lang="en">
      <body >
        <Providers>
          <Nav />
          <Login />
          <MiniCart />
          {data.children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
